Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ControleContatos.Filters;
using ControleContatos.Helper;
using ControleContatos.Models;
using ControleContatos.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Logging;

namespace ControleContatos.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ContatoController : Controller
    {
        private readonly ILogger<ContatoController> _logger;
        private readonly ISecao _secao;
        //Inserir a dependencia 
        private readonly IContatoRepository _contatoRepository;
        public ContatoController(ILogger<ContatoController> logger, IContatoRepository contatoRepository,ISecao secao)
        {
            _logger = logger;
            _contatoRepository = contatoRepository;
            _secao=secao;
        }

        public IActionResult Index()
        {
            var usuario=_secao.BuscarSecaoDoUsuario();
            List<ContatoModel> listaContatos = _contatoRepository.BuscarTodos(usuario.Id);
            return View(listaContatos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            var contato = _contatoRepository.BuscarContatoId(id);
            return View(contato);
        }
        //Metoto post para criar contato
        [HttpPost]
        public IActionResult Criar(ContatoModel contatoModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["Menssagem-sucesso"] = $"Contato {contatoModel.Nome} salvo com sucesso:";
                     var usuario=_secao.BuscarSecaoDoUsuario();
                     contatoModel.UsuarioId=usuario.Id;
                    _contatoRepository.AddContato(contatoModel);
                    return RedirectToAction("Index");
                }
                return View(contatoModel);

            }
            catch (System.Exception erro)
            {
                TempData["Menssagem-erro"] = $"Não foi possivel salvar o contato: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["Menssagem-sucesso"] = $"Contato alterado com sucesso:";
                     var usuario=_secao.BuscarSecaoDoUsuario();
                     contato.UsuarioId=usuario.Id;
                    _contatoRepository.Atualizar(contato);
                    return RedirectToAction("Index");
                }
                return View("Editar", contato);
            }
            catch (System.Exception erro)
            {
                TempData["Menssagem-erro"] = $"Não foi possivel alterar o contato: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepository.BuscarContatoId(id);
            return View(contato);
        }
        public async Task<IActionResult> Apagar(int id)
        {
            try
            {
                bool apagado = await _contatoRepository.ApagarContato(id);
                Console.WriteLine("Foi apagado:"+ apagado);
                if (apagado)
                {
                    TempData["Menssagem-sucesso"] = "Contato Apagado com sucesso!";
                    return RedirectToAction("Index");
                }else{
                     TempData["Menssagem-erro"]=$"Não foi possivel apagar o contato:";
                     return RedirectToAction("Index");
                }
                
            }
            catch (System.Exception erro)
            {
                TempData["Menssagem-erro"]=$"Não foi possivel apagar o contato, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Contato/ApagarConfirmacao.cshtml
@model ControleContatos.Models.ContatoModel
@{
    ViewData["Title"] = "Apagar Contato";
}
<div class="text-center">
    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>
</div>
<div class="d-grid gap-2">

    <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Apagar"
        asp-route-id="@Model.Id">Apagar</a>
    <a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="Index">Cancelar</a>
</div>

Views/Contato/Criar.cshtml
@model ControleContatos.Models.ContatoModel

@{
    ViewData["Title"] = "Criar Contato";
}
<div class="text-center">
    <h1 class="display-4">Criar novo contato</h1> 
    
</div>
<form asp-controller="Contato" asp-action="Criar"  method="post">
  <div class="mb-3">
    <label asp-for="Nome" class="form-label">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" aria-describedby="emailHelp" placeholder="Digite o nome do contato">
    @Html.ValidationMessageFor(x=>x.Nome)
  </div>
  <div class="mb-3">
    <label asp-for="Email" class="form-label">Email</label>
    <input type="text" asp-for="Email" class="form-control" aria-describedby="emailHelp" placeholder="Digite o email do contato">
    @Html.ValidationMessageFor(x=>x.Email)
  </div>
  <div class="mb-3">
    <label asp-for="Celular" class="form-label">Celular</label>
    <input type="text" asp-for="Celular" class="form-control" aria-describedby="emailHelp" placeholder="Digite o numero do contato">
    @Html.ValidationMessageFor(x=>x.Celular)
  </div>
  <button type="submit" class="btn btn-primary btn-block">Salvar</button>
  <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index">Voltar</a>
</form>

Views/Contato/Editar.cshtml
@model ControleContatos.Models.ContatoModel
@{
  ViewData["Title"] = "Editar Contato";
}
<div class="text-center">
  <h1 class="display-4">Editar contato</h1>

</div>
<form asp-controller="Contato" asp-action="Alterar" method="post">
  <input type="hidden" asp-for="Id">
  <div class="mb-3">
    <label asp-for="Nome" class="form-label">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" aria-describedby="emailHelp"
      placeholder="Digite o nome do contato">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="mb-3">
    <label asp-for="Email" class="form-label">Email</label>
    <input type="email" asp-for="Email" class="form-control" aria-describedby="emailHelp"
      placeholder="Digite o email do contato">
    @Html.ValidationMessageFor(x => x.Email)

  </div>
  <div class="mb-3">
    <label asp-for="Celular" class="form-label">Celular</label>
    <input type="text" asp-for="Celular" class="form-control" aria-describedby="emailHelp"
      placeholder="Digite o numero do contato">
    @Html.ValidationMessageFor(x => x.Celular)

  </div>

  <button type="submit" class="btn btn-primary btn-block">Alterar</button>
  <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index">Voltar</a>
</form>

Views/Contato/Index.cshtml
@model List<ControleContatos.Models.ContatoModel>//Especifica a model que a página vai usar
@{
    ViewData["Title"] = "Lista Contatos";
}
<div class="d-grid grap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-primary" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
</div>
<div class="text-center">
    @{
        //Mensagem de sucesso e erro
        if(TempData["Menssagem-sucesso"]!=null){
            <div class="alert alert-success" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
                @TempData["Menssagem-sucesso"]
            </div>
        }
        if(TempData["Menssagem-erro"]!=null){
            <div class="alert alert-danger" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
                @TempData["Menssagem-erro"]
            </div>
        }
    }

    <h1 class="display-4">Listagem de Contatos</h1>
    <table class="table table-striped" id="table-contatos">
        <thead>
            <tr class="table-primary">
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th scope="col">Data Cadastro</th>
                <th scope="col">#</th>
            </tr>
        </thead>
        <tbody>
            
            @if(Model!=null&&Model.Any()){
                int contador=1;
                
                foreach(var contato in Model){//Exibe a lista de contatos
                    <tr class="table-secondary">
                        <th scope="row">@contador</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>contato.DataCadastro</td>
                        <td>    
                            <div class="btn-group" role="group">
                                <a roule="button" class="btn btn-primary" asp-controller="Contato"
                                    asp-action="Editar" asp-route-id="@contato.Id">Editar</a>
                                <a roule="button" class="btn btn-danger" asp-route-id="@contato.Id"  asp-controller="Contato"
                                    asp-action="ApagarConfirmacao">Deletar</a>
                            </div>
                        </td>
                    </tr>
                    contador++;
                }
            }else{
                <tr class="add"><td valign="top" colspan="5">Nenhum contato encontrado</td></tr>
            }
           
        </tbody>
    </table>
</div>