Controllers/AlterarSenhaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ControleContatos.Helper;
using ControleContatos.Models;
using ControleContatos.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ControleContatos.Controllers
{
    //[Route("[controller]")]
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly ISecao _secao;
        public AlterarSenhaController(IUsuarioRepository usuarioRepository, ISecao secao)
        {
            _usuarioRepository = usuarioRepository;
            _secao = secao;
        }

        public IActionResult Index()

        {

            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _secao.BuscarSecaoDoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;
                if (ModelState.IsValid)
                {

                    _usuarioRepository.AtualizarSenha(alterarSenhaModel);
                    Console.WriteLine(alterarSenhaModel.ToString());
                    TempData["Menssagem-sucesso"] = "Senha Alterada com sucesso";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);
            }
            catch (System.Exception error)
            {
                TempData["Menssagem-erro"] = $"Ops! não conseguimos redefinir a sua senha, tente novamente. detalhe do erro: {error.Message}";
                return View("Index", alterarSenhaModel);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ControleContatos.Filters;
using ControleContatos.Models;
using ControleContatos.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ControleContatos.Controllers
{
    [PaginaRestritaSomenteAdm]
    public class UsuarioController : Controller
    {
        private readonly ILogger<UsuarioController> _logger;
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly IContatoRepository _contatoRepository;
        public UsuarioController(ILogger<UsuarioController> logger, IUsuarioRepository usuarioRepository,IContatoRepository contatoRepository)
        {
            _logger = logger;
            _usuarioRepository = usuarioRepository;
            _contatoRepository=contatoRepository;
        }

        public IActionResult Index()
        {
            List<UsuarioModel>? listUsuarios = _usuarioRepository.BuscarTodosUsuarios();

            return View(listUsuarios);
        }
        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["Menssagem-sucesso"] = $"Usuario {usuario.Nome} foi cadastrado com sucesso";
                    _usuarioRepository.AddUsuario(usuario);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(usuario);
                }
            }
            catch (System.Exception erro)
            {

                TempData["Menssagem-erro"] = $"Não foi possivel salvar o usuario: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
       public IActionResult Editar(int id){
            var usuarioModel=_usuarioRepository.BuscarPorId(id);
            UsuarioSemSenhaModel usuarioSemSenhaModel=new UsuarioSemSenhaModel(){
                        Id=usuarioModel.Id,
                        Nome=usuarioModel.Nome,
                        Login=usuarioModel.Login,
                        Email=usuarioModel.Email,
                        Perfil=usuarioModel.Perfil,
                    };
            return View(usuarioSemSenhaModel);
        }
        [HttpPost]
        public IActionResult Alterar(UsuarioSemSenhaModel usuarioSemSenhaModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioModel=new UsuarioModel(){
                        Id=usuarioSemSenhaModel.Id,
                        Nome=usuarioSemSenhaModel.Nome,
                        Login=usuarioSemSenhaModel.Login,
                        Email=usuarioSemSenhaModel.Email,
                        Perfil=usuarioSemSenhaModel.Perfil,

                    };
                    _usuarioRepository.Atualizar(usuarioModel);
                    TempData["Menssagem-sucesso"] = $"Usuário alterado com sucesso:";
                    return RedirectToAction("Index");
                }
                return View("Editar", usuarioSemSenhaModel);
            }
            catch (System.Exception erro)
            {
                TempData["Menssagem-erro"] = $"Não foi possivel alterar o contato: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        public IActionResult ApagarConfirmacao(int id)
        {
            var usuario = _usuarioRepository.BuscarPorId(id);
            return View(usuario);
        }
        public async Task<IActionResult> Apagar(int id)
        {
            try
            {
                bool apagado = await _usuarioRepository.Deletar(id);
                Console.WriteLine("Foi apagado:" + apagado);
                if (apagado)
                {
                    TempData["Menssagem-sucesso"] = "Usuario removido com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Menssagem-erro"] = $"Não foi possivel remover o usuario:";
                    return RedirectToAction("Index");
                }

            }
            catch (System.Exception erro)
            {
                TempData["Menssagem-erro"] = $"Não foi possivel apagar o usuário, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        public IActionResult ListarContatosPorUsuarioId(int id){
            var listaContatos=_contatoRepository.BuscarTodos(id);
            return PartialView("_ContatosUsuario",listaContatos);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/AlterarSenha/Index.cshtml
@model ControleContatos.Models.AlterarSenhaModel?
@{
  ViewData["Title"] = "Alterar senha";
}
@{
  //Mensagem de sucesso e erro
  if (TempData["Menssagem-sucesso"] != null)
  {
    <div class="alert alert-success" role="alert">
      <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
      @TempData["Menssagem-sucesso"]
    </div>
  }
  if (TempData["Menssagem-erro"] != null)
  {
    <div class="alert alert-danger" role="alert">
      <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
      @TempData["Menssagem-erro"]
    </div>
  }
}

<div class="text-center">
  <h1 class="display-4">Alterar senha</h1>

</div>
<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

  <div class="mb-3">
    <label asp-for="SenhaAtual" class="form-label">Senha Atual</label>
    <input type="password" asp-for="SenhaAtual" class="form-control" aria-describedby="emailHelp"
      placeholder="Digite a sua senha altual">
    @Html.ValidationMessageFor(x => x.SenhaAtual)
  </div>
  <div class="mb-3">
    <label asp-for="NovaSenha" class="form-label">Nova Senha</label>
    <input type="password" asp-for="NovaSenha" class="form-control" aria-describedby="emailHelp"
      placeholder="Digite a nova senha">
    @Html.ValidationMessageFor(x => x.NovaSenha)
  </div>
  <div class="mb-3">
    <label asp-for="ConfirmarSenha" class="form-label">Confirmar Senha</label>
    <input type="password" asp-for="ConfirmarSenha" class="form-control" aria-describedby="emailHelp"
      placeholder="Confirme a nova senha">
    @Html.ValidationMessageFor(x => x.ConfirmarSenha)
  </div>

  <div class="d-grid gap-2">
    <button class="btn btn-primary" type="submit">Alterar</button>
    <a class="btn btn-secondary" type="button" asp-controller="Usuario" asp-action="Index">Voltar</a>
  </div>
</form>